### ISSUE TITLE
Unable to connect with pg_tmp database in docker

### ISSUE THREAD

**Issue by agabarre97** [eradman/ephemeralpg#5]
I have pg_tmp installed in a postgresql base docker. I want to create a database in docker and stablish a connection outside (own machine or other docker) for testing purposes. However, I've found some problems with that. 

Steps:

1. I have a docker-compose which launches the docker with postgresql and pg_tmp:
```yaml
version: '3'

services:
  test_pg_tmp:
    image: postgres-pg_tmp
    container_name: test_pg_tmp
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
      - 5433:5433
```

2. Then, I create a database in the docker:

```bash
$ docker exec -it test_pg_tmp /bin/bash
$ pg_tmp -t -p 5433
postgresql://postgres@127.0.0.1:5433/test
```
3. Finally, I try to connect with my machine to this address
```bash
$ psql postgresql://postgres@127.0.0.1:5433/test
psql: connection to server at "127.0.0.1", port 5433 failed: FATAL:  no pg_hba.conf entry for host "my_host_ip", user "postgres", database "test", no encryption
```

As I get this error, I've edited `pg_hba.conf` file, adding new lines to trust everything:

```bash
# warning trust is enabled for all connections
# see https://www.postgresql.org/docs/12/auth-trust.html
host all all all trust
host all all 0.0.0.0/0 md5
host all all my_host_ip/24 trust
host all all 127.0.0.1/24 trust
```

I was wandering if `pg_tmp` is not thought to be used in another docker. Maybe It's necessary to be used in the same instance of client service.
